# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-10 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niji', '0002_announcement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='append_file',
            field=models.FileField(default=1, upload_to='uploads/forum/files/', verbose_name='append_file'),
            preserve_default=False,
        ),
    ]
