# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-12 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('niji', '0003_topic_append_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='append_file',
            field=models.FileField(default='', upload_to='uploads/forum/files/', verbose_name='append_file'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/forum/covers/', verbose_name='image'),
        ),
    ]
