# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-12 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niji', '0004_auto_20200212_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(blank=True, max_length=3000, verbose_name='content'),
        ),
    ]
