# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-16 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niji', '0006_auto_20200212_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='content',
        ),
        migrations.AddField(
            model_name='announcement',
            name='content_raw',
            field=models.TextField(blank=True, max_length=2000, verbose_name='raw content'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='content_rendered',
            field=models.TextField(blank=True, max_length=3000, verbose_name='rendered content'),
        ),
    ]
