# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-07 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niji', '0006_auto_20200208_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='brief',
            field=models.CharField(max_length=120, verbose_name='brief'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='cover_img',
            field=models.CharField(max_length=120, verbose_name='cover img'),
        ),
    ]
