# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-07 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niji', '0008_auto_20200208_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content_raw',
            field=models.TextField(max_length=2000, verbose_name='raw content'),
        ),
    ]
