# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-07 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niji', '0009_auto_20200208_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('content', models.TextField(blank=True, max_length=3000, verbose_name='content')),
            ],
        ),
    ]
