# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-07 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('niji', '0012_auto_20200208_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='published time'),
            preserve_default=False,
        ),
    ]
