# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-07 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niji', '0013_announcement_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='view count'),
        ),
    ]
