# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-08 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niji', '0014_announcement_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='brief',
        ),
    ]
