# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-08 10:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('niji', '0015_remove_topic_brief'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, verbose_name='code')),
                ('status', models.IntegerField(default=0, verbose_name='status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailcodes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': '类别', 'verbose_name_plural': '类别'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order', '-pub_date'], 'verbose_name': '帖子', 'verbose_name_plural': '帖子'},
        ),
        migrations.AlterField(
            model_name='node',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='对该类别的描述'),
        ),
        migrations.AlterField(
            model_name='node',
            name='title',
            field=models.CharField(max_length=30, verbose_name='类别'),
        ),
    ]
