# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-08 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niji', '0016_auto_20200208_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcode',
            name='user',
        ),
        migrations.AddField(
            model_name='emailcode',
            name='email',
            field=models.CharField(default=1, max_length=64, verbose_name='email'),
            preserve_default=False,
        ),
    ]
