# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-19 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niji', '0017_auto_20200208_1925'),
        ('niji', '0007_auto_20200216_1737'),
    ]

    operations = [
    ]
